version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: usersdb
    ports:
      - "9002:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: pass123
      DB_NAME: usersdb
      DB_PORT: 5432
    ports:
      - "9000:9000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "9001:80"
    depends_on:
      - backend

volumes:
  pgdata:
